function p = path_init()
    p = [cd,...
        "EM Images\",...
        "ExportedPictures\",...
        "OD Images\",...
        "C:\ProgramData\MATLAB\SupportPackages\R2022b\mex\supportpackages\mingw",...
        "C:\ProgramData\MATLAB\SupportPackages\R2022b\toolbox\nnet\supportpackages\alexnet",...
        "D:\Michael Gross\Documents\MAT499 Images",...
        "D:\Michael Gross\Documents\MAT499 Images\Raw Images",...
        "D:\Michael Gross\Documents\MAT499 Images\Training Data"];

    for n = 1:numel(p)
        addpath(p(n));
    end
end

